### ISSUE TITLE
Connecting to host error with version upgrade

### ISSUE THREAD

**Issue by alihamza1214** [cmp-202/ssh2shell#89]
It worked well with 1.9.1 but when I upgraded the packages the existing code started giving error on connecting to remote from my laptop.

Error:
  this.connection = new require('ssh2')();
                                        ^
TypeError: (intermediate value) is not a function
    at new SSH2Shell (D:\Clicky Live Vue\clicky\node_modules\ssh2shell\lib\ssh2shell.js:664:44)

**Comment by cmp-202** [comment]
Hi,
This was fixed in [1.9.7](https://github.com/cmp-202/ssh2shell/releases/tag/1.9.7).
The latest NPM version is good to go.
Cheers,

Andrew
